# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:02
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_team_data(apps, schema_editor):
    Team = apps.get_model('nfl','Team')
    with open('teams.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            Team.objects.create(city=row[0],name=row[1],wins=row[2],losses=row[3],
            ties=row[4],div=row[5])
    raise Exception('asdfasdf')

class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
    #migrations.RunPython(add_team_data)
    ]
