# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 20:06
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_team_data(apps, schema_editor):
    Team = apps.get_model('nfl','Team')
    with open('teams.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            print(row[1])
            Team.objects.create(city=row[0],name=row[1],wins=row[2],losses=row[3],
            ties=row[4],div=row[5])

class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_auto_20170123_2002'),
    ]

    operations = [
    migrations.RunPython(add_team_data)
    ]
